FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
RUN mkdir -p uploads # <-- Garante que a pasta existe no container

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]