version: "3.8"

services:
  # --- Serviço do Backend ---
  backend:
    build: ./backend
    container_name: capiba-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    env_file:
      - ./backend/.env

  # --- Serviço do Frontend ---
  frontend:
    build: ./frontend
    container_name: capiba-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000

