FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl bash git

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN mkdir -p uploads

EXPOSE 3000

CMD ["npm", "start"]
